/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException {
//        Gson gson = new Gson();
//        TypeDTO[] myTypes = gson.fromJson(new FileReader("quotes.json"), TypeDTO[].class);
//        System.out.println(gson.toJson(myTypes));

        try {
            Gson gson = new Gson();
            Reader reader = Files.newBufferedReader(Paths.get("quotes.json"));
            List<Quote> author = new Gson().fromJson(reader, new TypeToken<List<Quote>>() {
            }.getType());
//        List<Quote> authorSaid = new Gson().fromJson(reader, new TypeToken<List<User>>() {}.getType());
            author.forEach(System.out::println);
            reader.close();
        } catch (Exception ex){
            ex.printStackTrace();
        }

        File jsonedFile = new File("src/main/java/resources/jsonedFile.json");
        jsonedFile.createNewFile();
        FileWriter jsonedFileWriter = new FileWriter("src/main/java/resources/jsonedFile.json");
        jsonedFileWriter.close();

//        FileReader barryScan = new FileReader(new File("src/main/resources/quotes.json"));
//        System.out.println("stuff" + barryScan.ready());

//        Scanner jsonScanner = new Scanner(new File("src/main/resources/quotes.json"));
//        String allTheJson = jsonScanner.nextLine();
//        Quote authorSaid = gson.fromJson(allTheJson, Quote.class);
//        System.out.println(authorSaid);
    }
    class TypeDTO {
        String author;
        String text;
    }
    class ItemDTO{
        String author;
        String text;
    }

}
