/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws FileNotFoundException {

        try {
            Gson gson = new Gson();

            Reader reader = Files.newBufferedReader(Paths.get("src/main/resources/quotes.json"));

            Quote[] quote = gson.fromJson(reader, Quote[].class);


            int randomNum = (int)(Math.random() * quote.length);
            System.out.println(quote[randomNum]);

            reader.close();

            }catch (Exception ex) {
            ex.printStackTrace();

        }
    }
    class TypeDTO {
        String author;
        String text;
    }
    class ItemDTO{
        String author;
        String text;
    }

}
